name: linter
run-name: Code Linter
on:
 pull_request:
   branches: main
jobs:
  linter:
    runs-on: self-hosted
    steps:
      - shell: bash
        run: echo "this is running on a self hosted runner"
